name: ImprovedTimber
version: 2.0
author: MaLo
main: me.malo.timbermod.timber.Timber
api-version: 1.16
softdepend: [WorldGuard]

permissions:
  timber.*:
    default: true
  timber.use:
    default: true
  timber.toggle:
    default: true

commands:
  toggletimber:
    description: Toggle the timber function
    usage: /toggletimber
    permission: timber.toggle