#
#    xxxxxxxxxx    xx    xxxx    xxxx    xxxxxx     xxxxxx    xxxxxx
#        xx        xx    xx xx  xx xx    xx   xx    xx        xx   xx
#        xx        xx    xx  xxxx  xx    xx   xx    xx        xx   xx
#        xx        xx    xx   xx   xx    xxxxxx     xxxxxx    xxxxxx
#        xx        xx    xx        xx    xx   xx    xx        xx xx
#        xx        xx    xx        xx    xx   xx    xx        xx  xx
#        xx        xx    xx        xx    xxxxxx     xxxxxx    xx   xx
#

# Not much to do here.
# This sets the distance between the checked block
# and the originally mined block
maxChop: 8
