#
#    xxxxxxxxxx    xx    xxxx    xxxx    xxxxxx     xxxxxx    xxxxxx
#        xx        xx    xx xx  xx xx    xx   xx    xx        xx   xx
#        xx        xx    xx  xxxx  xx    xx   xx    xx        xx   xx
#        xx        xx    xx   xx   xx    xxxxxx     xxxxxx    xxxxxx
#        xx        xx    xx        xx    xx   xx    xx        xx xx
#        xx        xx    xx        xx    xx   xx    xx        xx  xx
#        xx        xx    xx        xx    xxxxxx     xxxxxx    xx   xx
#                                                                       by 12xx12

# This sets the distance between the checked block
# and the originally mined block
maxChop: 8

# This enables the logging feature if you are interested
logging: false
