name: ImprovedTimber
version: 1.0
author: MaLo
main: de.malo.timber.Timber
api-version: 1.15
softdepend: [WorldGuard]


commands:
  toggletimber:
    description: Toggle the timber function
    usage: /toggletimber